<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Edit3, Flag, HandHeart, MapPin, Phone } from 'lucide-vue-next'
import { lostFoundApi } from '@/api'
import type { LostFound } from '@/types'
import { formatTime, parseImages } from '@/utils/format'
import { useAuthStore } from '@/stores/auth'
import ImageGallery from '@/components/ImageGallery.vue'
import PageState from '@/components/PageState.vue'
import ReportDialog from '@/components/ReportDialog.vue'
import StatusTag from '@/components/StatusTag.vue'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const id = Number(route.params.id); const record = ref<LostFound>(); const loading = ref(true); const error = ref(''); const claimOpen = ref(false); const reportOpen = ref(false); const submitting = ref(false)
const claim = reactive({ message: '', contact: '', verification: '' }); const isOwner = computed(() => auth.session?.userId === record.value?.userId)
async function load(){ loading.value=true;error.value='';try{record.value=await lostFoundApi.get(id)}catch(e){error.value=(e as Error).message}finally{loading.value=false} }
function loginFirst(){if(!auth.isLoggedIn){router.push({path:'/auth/login',query:{redirect:route.fullPath}});return false}return true}
async function submitClaim(){if(!claim.message.trim()||!claim.contact.trim())return ElMessage.warning('请填写认领说明和联系方式');submitting.value=true;try{await lostFoundApi.claim(id,claim);ElMessage.success('认领申请已提交');claimOpen.value=false}finally{submitting.value=false}}
async function status(value:string,label:string){await ElMessageBox.confirm(`确认将状态更新为“${label}”吗？`,'更新状态',{type:'warning'});await lostFoundApi.status(id,value);ElMessage.success('状态已更新');load()}
onMounted(load)
</script>
<template><PageState :loading="loading" :error="error" :empty="!record" @retry="load"><template #content><div v-if="record"><div class="detail-layout"><ImageGallery :images="parseImages(record.images)" :alt="record.title" /><aside class="detail-panel"><div style="display:flex;justify-content:space-between"><el-tag :type="record.type==='LOST'?'warning':'success'">{{ record.type==='LOST'?'寻物启事':'招领信息' }}</el-tag><StatusTag :status="record.status" /></div><h1>{{ record.title }}</h1><div class="detail-meta"><span><MapPin :size="15" /> {{ record.location }}</span><span>时间：{{ formatTime(record.lostTime) }}</span></div><div class="owner-row"><el-avatar :src="record.publisherAvatar">{{ (record.publisherNickname||'用户').slice(0,1) }}</el-avatar><div><strong>{{ record.publisherNickname || `用户 ${record.userId}` }}</strong><div style="font-size:12px;color:var(--ink-500)">发布于 {{ formatTime(record.createTime,'MM-DD HH:mm') }}</div></div></div><p><Phone :size="15" /> 联系方式：{{ auth.isLoggedIn ? record.contact : '登录后查看' }}</p><div v-if="!isOwner" class="detail-actions"><el-button type="primary" :disabled="auth.isMuted || !['IN_PROGRESS','PROCESSING'].includes(record.status)" @click="loginFirst()&&(claimOpen=true)"><HandHeart :size="17" />提交认领</el-button><el-button @click="loginFirst()&&(reportOpen=true)"><Flag :size="16" />举报</el-button></div><div v-else class="detail-actions"><el-button type="primary" @click="router.push(`/lost-found/${id}/edit`)"><Edit3 :size="17" />编辑信息</el-button><el-button v-if="record.status==='IN_PROGRESS'" @click="status('PROCESSING','处理中')">进入处理</el-button><el-button v-if="['IN_PROGRESS','PROCESSING'].includes(record.status)" @click="status(record.type==='LOST'?'FOUND':'RETURNED',record.type==='LOST'?'已找回':'已归还')">完成</el-button><el-button v-if="['IN_PROGRESS','PROCESSING'].includes(record.status)" @click="status('CLOSED','已关闭')">关闭</el-button></div></aside></div><section class="description"><h2 style="font-size:18px">详细说明</h2>{{ record.description || '发布者暂未填写详细说明。' }}</section><el-dialog v-model="claimOpen" title="提交认领申请" width="min(520px,92vw)"><el-form label-position="top"><el-form-item label="认领说明" required><el-input v-model="claim.message" type="textarea" :rows="3" maxlength="500" /></el-form-item><el-form-item label="联系方式" required><el-input v-model="claim.contact" maxlength="100" /></el-form-item><el-form-item label="验证信息"><el-input v-model="claim.verification" type="textarea" :rows="3" maxlength="500" placeholder="描述只有物主知道的特征，管理员将保密处理" /></el-form-item></el-form><template #footer><el-button @click="claimOpen=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submitClaim">提交申请</el-button></template></el-dialog><ReportDialog v-model="reportOpen" target-type="LOST_FOUND" :target-id="id" /></div></template></PageState></template>
