<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { adminApi } from '@/api'
import type { Report } from '@/types'
import { formatTime } from '@/utils/format'
import StatusTag from '@/components/StatusTag.vue'
const rows=ref<Report[]>([]);const loading=ref(true);const total=ref(0);const page=ref(1);const status=ref('PENDING');const open=ref(false);const selected=ref<Report>();const submitting=ref(false);const form=reactive({status:'RESOLVED',reviewNote:''})
async function load(){loading.value=true;try{const data=await adminApi.reports({page:page.value,size:10,status:status.value||undefined});rows.value=data.records;total.value=data.total}finally{loading.value=false}}
function handle(row:Report,value:string){selected.value=row;form.status=value;form.reviewNote='';open.value=true}
async function submit(){if(!selected.value)return;submitting.value=true;try{await adminApi.handleReport(selected.value.id,form);ElMessage.success('举报已处理');open.value=false;load()}finally{submitting.value=false}}
onMounted(load)
</script>
<template><div><div class="page-heading"><div><h1>举报处理</h1><p>核查社区举报并记录处理结论</p></div></div><div class="surface table-surface"><div class="data-toolbar"><el-radio-group v-model="status" @change="page=1;load()"><el-radio-button value="PENDING">待处理</el-radio-button><el-radio-button value="RESOLVED">已处理</el-radio-button><el-radio-button value="DISMISSED">已忽略</el-radio-button><el-radio-button value="">全部</el-radio-button></el-radio-group></div><el-table v-loading="loading" :data="rows"><el-table-column prop="targetLabel" label="举报对象" min-width="170"><template #default="{row}">{{ row.targetLabel||`${row.targetType} #${row.targetId}` }}</template></el-table-column><el-table-column prop="reason" label="原因" min-width="130" /><el-table-column label="风险" width="90"><template #default="{row}"><StatusTag :status="row.riskLevel" /></template></el-table-column><el-table-column prop="description" label="问题说明" min-width="180" show-overflow-tooltip /><el-table-column label="状态" width="100"><template #default="{row}"><StatusTag :status="row.status" /></template></el-table-column><el-table-column label="时间" width="150"><template #default="{row}">{{ formatTime(row.createTime) }}</template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><template v-if="row.status==='PENDING'"><el-button text type="primary" @click="handle(row,'RESOLVED')">确认处理</el-button><el-button text @click="handle(row,'DISMISSED')">忽略</el-button></template></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" layout="prev,pager,next" :page-size="10" :total="total" @current-change="load" /></div></div><el-dialog v-model="open" title="处理举报" width="min(480px,92vw)"><el-form label-position="top"><el-form-item label="处理结论"><el-segmented v-model="form.status" :options="[{label:'确认处理',value:'RESOLVED'},{label:'驳回举报',value:'DISMISSED'}]" /></el-form-item><el-form-item label="处理备注"><el-input v-model="form.reviewNote" type="textarea" :rows="4" maxlength="500" /></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">提交结论</el-button></template></el-dialog></div></template>
